// Env var name constants
export const CREDENTIAL_PROXY_PORT_ENV = "CREDENTIAL_PROXY_PORT";
export const CREDENTIAL_PROXY_URL_ENV = "CREDENTIAL_PROXY_URL";
export const DOPPLER_SERVICE_TOKEN_ENV = "DOPPLER_SERVICE_TOKEN";
export const DOPPLER_TOKEN_ENV = "DOPPLER_TOKEN";
export const DOPPLER_PROJECT_ENV = "DOPPLER_PROJECT";
export const DOPPLER_CONFIG_ENV = "DOPPLER_CONFIG";
export const SUPABASE_URL_ENV = "SUPABASE_URL";
export const SUPABASE_SERVICE_KEY_ENV = "SUPABASE_SERVICE_KEY";

// Default values
export const DEFAULT_PORT = 7447;
