/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedPProjectNameRouteImport } from './routes/_authenticated/p.$projectName'
import { Route as AuthenticatedChatNewRouteImport } from './routes/_authenticated/chat.new'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedActivityProcessIdRouteImport } from './routes/_authenticated/activity.$processId'
import { Route as AuthenticatedPProjectNameIndexRouteImport } from './routes/_authenticated/p.$projectName/index'
import { Route as AuthenticatedPProjectNameTasksRouteImport } from './routes/_authenticated/p.$projectName/tasks'
import { Route as AuthenticatedPProjectNameActivityProcessIdRouteImport } from './routes/_authenticated/p.$projectName/activity.$processId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPProjectNameRoute =
  AuthenticatedPProjectNameRouteImport.update({
    id: '/p/$projectName',
    path: '/p/$projectName',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatNewRoute = AuthenticatedChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityProcessIdRoute =
  AuthenticatedActivityProcessIdRouteImport.update({
    id: '/activity/$processId',
    path: '/activity/$processId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPProjectNameIndexRoute =
  AuthenticatedPProjectNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPProjectNameRoute,
  } as any)
const AuthenticatedPProjectNameTasksRoute =
  AuthenticatedPProjectNameTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedPProjectNameRoute,
  } as any)
const AuthenticatedPProjectNameActivityProcessIdRoute =
  AuthenticatedPProjectNameActivityProcessIdRouteImport.update({
    id: '/activity/$processId',
    path: '/activity/$processId',
    getParentRoute: () => AuthenticatedPProjectNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/activity/$processId': typeof AuthenticatedActivityProcessIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/p/$projectName': typeof AuthenticatedPProjectNameRouteWithChildren
  '/p/$projectName/tasks': typeof AuthenticatedPProjectNameTasksRoute
  '/p/$projectName/': typeof AuthenticatedPProjectNameIndexRoute
  '/p/$projectName/activity/$processId': typeof AuthenticatedPProjectNameActivityProcessIdRoute
}
export interface FileRoutesByTo {
  '/cli-auth': typeof CliAuthRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/activity/$processId': typeof AuthenticatedActivityProcessIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/chat/new': typeof AuthenticatedChatNewRoute
  '/p/$projectName/tasks': typeof AuthenticatedPProjectNameTasksRoute
  '/p/$projectName': typeof AuthenticatedPProjectNameIndexRoute
  '/p/$projectName/activity/$processId': typeof AuthenticatedPProjectNameActivityProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cli-auth': typeof CliAuthRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activity/$processId': typeof AuthenticatedActivityProcessIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/chat/new': typeof AuthenticatedChatNewRoute
  '/_authenticated/p/$projectName': typeof AuthenticatedPProjectNameRouteWithChildren
  '/_authenticated/p/$projectName/tasks': typeof AuthenticatedPProjectNameTasksRoute
  '/_authenticated/p/$projectName/': typeof AuthenticatedPProjectNameIndexRoute
  '/_authenticated/p/$projectName/activity/$processId': typeof AuthenticatedPProjectNameActivityProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-auth'
    | '/dev'
    | '/login'
    | '/onboarding'
    | '/tasks'
    | '/activity/$processId'
    | '/chat/$id'
    | '/chat/new'
    | '/p/$projectName'
    | '/p/$projectName/tasks'
    | '/p/$projectName/'
    | '/p/$projectName/activity/$processId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cli-auth'
    | '/dev'
    | '/login'
    | '/onboarding'
    | '/tasks'
    | '/'
    | '/activity/$processId'
    | '/chat/$id'
    | '/chat/new'
    | '/p/$projectName/tasks'
    | '/p/$projectName'
    | '/p/$projectName/activity/$processId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/cli-auth'
    | '/dev'
    | '/login'
    | '/onboarding'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/activity/$processId'
    | '/_authenticated/chat/$id'
    | '/_authenticated/chat/new'
    | '/_authenticated/p/$projectName'
    | '/_authenticated/p/$projectName/tasks'
    | '/_authenticated/p/$projectName/'
    | '/_authenticated/p/$projectName/activity/$processId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CliAuthRoute: typeof CliAuthRoute
  DevRoute: typeof DevRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p/$projectName': {
      id: '/_authenticated/p/$projectName'
      path: '/p/$projectName'
      fullPath: '/p/$projectName'
      preLoaderRoute: typeof AuthenticatedPProjectNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/new': {
      id: '/_authenticated/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof AuthenticatedChatNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity/$processId': {
      id: '/_authenticated/activity/$processId'
      path: '/activity/$processId'
      fullPath: '/activity/$processId'
      preLoaderRoute: typeof AuthenticatedActivityProcessIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/p/$projectName/': {
      id: '/_authenticated/p/$projectName/'
      path: '/'
      fullPath: '/p/$projectName/'
      preLoaderRoute: typeof AuthenticatedPProjectNameIndexRouteImport
      parentRoute: typeof AuthenticatedPProjectNameRoute
    }
    '/_authenticated/p/$projectName/tasks': {
      id: '/_authenticated/p/$projectName/tasks'
      path: '/tasks'
      fullPath: '/p/$projectName/tasks'
      preLoaderRoute: typeof AuthenticatedPProjectNameTasksRouteImport
      parentRoute: typeof AuthenticatedPProjectNameRoute
    }
    '/_authenticated/p/$projectName/activity/$processId': {
      id: '/_authenticated/p/$projectName/activity/$processId'
      path: '/activity/$processId'
      fullPath: '/p/$projectName/activity/$processId'
      preLoaderRoute: typeof AuthenticatedPProjectNameActivityProcessIdRouteImport
      parentRoute: typeof AuthenticatedPProjectNameRoute
    }
  }
}

interface AuthenticatedPProjectNameRouteChildren {
  AuthenticatedPProjectNameTasksRoute: typeof AuthenticatedPProjectNameTasksRoute
  AuthenticatedPProjectNameIndexRoute: typeof AuthenticatedPProjectNameIndexRoute
  AuthenticatedPProjectNameActivityProcessIdRoute: typeof AuthenticatedPProjectNameActivityProcessIdRoute
}

const AuthenticatedPProjectNameRouteChildren: AuthenticatedPProjectNameRouteChildren =
  {
    AuthenticatedPProjectNameTasksRoute: AuthenticatedPProjectNameTasksRoute,
    AuthenticatedPProjectNameIndexRoute: AuthenticatedPProjectNameIndexRoute,
    AuthenticatedPProjectNameActivityProcessIdRoute:
      AuthenticatedPProjectNameActivityProcessIdRoute,
  }

const AuthenticatedPProjectNameRouteWithChildren =
  AuthenticatedPProjectNameRoute._addFileChildren(
    AuthenticatedPProjectNameRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivityProcessIdRoute: typeof AuthenticatedActivityProcessIdRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedChatNewRoute: typeof AuthenticatedChatNewRoute
  AuthenticatedPProjectNameRoute: typeof AuthenticatedPProjectNameRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivityProcessIdRoute: AuthenticatedActivityProcessIdRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedChatNewRoute: AuthenticatedChatNewRoute,
  AuthenticatedPProjectNameRoute: AuthenticatedPProjectNameRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CliAuthRoute: CliAuthRoute,
  DevRoute: DevRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
