import { resolve } from 'path'
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs'
import type { PreflightHook } from '../../types.js'
import { dirname } from 'path'
import { fileURLToPath } from 'url'
const __dirname = dirname(fileURLToPath(import.meta.url))

// Note: gpt-5.3-codex API access not yet available (Feb 2026)
const MODEL = 'gpt-5.2-codex'

/**
 * Preflight hook that sets up Codex configuration
 * Skills are synced separately by the sync module to .agents/skills
 * Also copies CODEX-ADDENDUM.md as AGENTS.md for Claude→Codex prompt compatibility
 */
const setupCodexConfig: PreflightHook = {
  name: 'setup-codex-config',
  async run(context) {
    const { configDir, workingDir } = context

    // Create .codex directory
    mkdirSync(configDir, { recursive: true })

    // Create .agents/skills directory for skill sync destination
    const agentsSkillsDir = resolve(workingDir, '.agents', 'skills')
    mkdirSync(agentsSkillsDir, { recursive: true })

    // Create config.toml for headless operation
    // Point skills.config to .agents/skills where sync copies them
    const configContent = `# Codex configuration for headless operation
# Auto-generated by outcomes-optimizer

# Model configuration
model = "${MODEL}"
model_reasoning_effort = "high"

# Full headless - no approval pauses
approval_policy = "never"

# Skills configuration - synced to .agents/skills by outcomes-optimizer
[[skills.config]]
path = ".agents/skills"
enabled = true
`
    writeFileSync(resolve(configDir, 'config.toml'), configContent)

    // Copy CODEX-ADDENDUM.md as AGENTS.md for Claude→Codex prompt compatibility
    // Codex automatically reads AGENTS.md for project-specific instructions
    const addendumPath = resolve(__dirname, 'CODEX-ADDENDUM.md')
    const agentsMdPath = resolve(workingDir, 'AGENTS.md')
    if (existsSync(addendumPath)) {
      const addendumContent = readFileSync(addendumPath, 'utf-8')
      writeFileSync(agentsMdPath, addendumContent)
    }
  }
}

export const codexPreflightHooks: PreflightHook[] = [setupCodexConfig]
